[workspace]
members = [
    "uniswap-libs",
    "uniswap-erc20",
    "uniswap-factory",
    "uniswap-pair",
    "uniswap-tests",
    "erc20"
]

# enable overflow checks to make it behave like we used SafeMath in solidity
[profile.release]
overflow-checks = true